apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: gustav0thethird
  description: GitHub profile README
  annotations:
    backstage.io/techdocs-ref: dir:.
    gitlab.com/project-slug: yditj/projects/archive/gustav0thethird
  links:
    - url: https://github.com/gustav0thethird/gustav0thethird
      title: GitHub
      icon: github
  tags:
    - profile
    - readme
    - archive
spec:
  type: documentation
  lifecycle: experimental
  owner: gtully
  system: archive
