site_name: gustav0thethird
site_description: GitHub profile README
plugins:
- techdocs-core
nav:
- Overview: index.md
- Readme: readme.md
- CI Configuration: ci-configuration.md
- Backstage Integration: backstage-integration.md
